export const defaultSettings = {
  booksPath: "/mnt/media/Books",
  audiobooksPath: "/mnt/media/Audiobooks",
  downloadsPath: "/mnt/media/Downloads",
  sabEnabled: "true",
  sabUrl: "http://localhost:8080",
  sabApiKey: "",
  sabEbookCategory: "ebooks",
  sabAudiobookCategory: "audiobooks",
  qbittorrentEnabled: "false",
  qbittorrentUrl: "http://localhost:8081",
  qbittorrentUsername: "",
  qbittorrentPassword: "",
  qbittorrentEbookCategory: "ebooks",
  qbittorrentAudiobookCategory: "audiobooks",
  prowlarrUrl: "http://localhost:9696",
  prowlarrApiKey: "",
  prowlarrEbookCategories: "7020,8010",
  prowlarrAudiobookCategories: "3030,8010",
  hardcoverEnabled: "false",
  hardcoverEndpoint: "https://api.hardcover.app/v1/graphql",
  hardcoverApiKey: "",
  audiobookshelfUrl: "http://localhost:13378",
  audiobookshelfApiKey: "",
  homepageApiKey: "",
  autoImportThreshold: "90",
  autoRequestThreshold: "85",
  manualReviewThreshold: "70",
  importMode: "move",
  keepOriginalFiles: "false",
  deleteSourceFilesAfterImport: "true",
  allowOverwrite: "false",
  ignoreSamples: "true",
  ignoreExtras: "true",
  pollingIntervalSeconds: "60"
};

export type SettingsMap = typeof defaultSettings;
